const fs = require("fs");
const path = require("path");
const https = require("https");

const SOURCE_URL =
  "https://raw.githubusercontent.com/google/fonts/main/ofl/notosans/METADATA.pb";

const FONT_REPO_API =
  "https://api.github.com/repos/google/fonts/git/trees/main?recursive=1";

const marketingFavorites = [
  "Inter",
  "Poppins",
  "Montserrat",
  "DM Sans",
  "Manrope",
  "Roboto",
  "Open Sans",
  "Lato",
  "Nunito",
  "Rubik",
  "Work Sans",
  "Source Sans 3",
  "Playfair Display",
  "Merriweather",
  "Oswald",
  "Bebas Neue",
  "Anton",
  "Archivo",
  "Barlow",
  "Figtree",
];

const tagMap = {
  Inter: ["SaaS", "Tech", "Modern", "Professional", "Minimal"],
  Poppins: ["Marketing", "Retail", "Modern", "Friendly"],
  Montserrat: ["Premium", "Modern", "Ecommerce", "Bold"],
  "DM Sans": ["SaaS", "Minimal", "Modern", "Apps"],
  Manrope: ["Tech", "Modern", "Clean", "Professional"],
  Roboto: ["Universal", "Clean", "Professional"],
  "Open Sans": ["Readable", "Friendly", "Professional"],
  Lato: ["Friendly", "Modern", "Professional"],
  Nunito: ["Friendly", "Soft", "Consumer"],
  Rubik: ["Modern", "Playful", "Digital"],
  "Work Sans": ["Modern", "Professional", "Clean"],
  "Source Sans 3": ["Editorial", "Readable", "Professional"],
  "Playfair Display": ["Luxury", "Fashion", "Jewelry", "Elegant"],
  Merriweather: ["Editorial", "Premium", "Trustworthy"],
  Oswald: ["Fitness", "Sports", "Bold", "Impact"],
  "Bebas Neue": ["Fitness", "Automotive", "Sports", "Bold"],
  Anton: ["Retail", "Sales", "Bold", "High Impact"],
  Archivo: ["Bold", "Modern", "Campaigns"],
  Barlow: ["Tech", "Modern", "Friendly"],
  Figtree: ["Modern", "SaaS", "Clean"],
};

function fetchJson(url) {
  return new Promise((resolve, reject) => {
    https
      .get(
        url,
        {
          headers: {
            "User-Agent": "AdGen-MCM-Font-Generator",
          },
        },
        (res) => {
          let data = "";

          res.on("data", (chunk) => {
            data += chunk;
          });

          res.on("end", () => {
            try {
              resolve(JSON.parse(data));
            } catch (err) {
              reject(err);
            }
          });
        }
      )
      .on("error", reject);
  });
}

function guessCategory(pathName) {
  if (pathName.includes("/ofl/")) return "google-font";
  if (pathName.includes("/apache/")) return "google-font";
  if (pathName.includes("/ufl/")) return "google-font";
  return "google-font";
}

function familyFromPath(pathName) {
  const parts = pathName.split("/");
  const folder = parts[1];

  if (!folder) return null;

  return folder
    .replace(/([a-z])([A-Z])/g, "$1 $2")
    .replace(/-/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

async function main() {
  console.log("Fetching Google Fonts repository catalog...");

  const data = await fetchJson(FONT_REPO_API);

  const metadataFiles = data.tree.filter(
    (item) =>
      item.path.endsWith("METADATA.pb") &&
      (item.path.startsWith("ofl/") ||
        item.path.startsWith("apache/") ||
        item.path.startsWith("ufl/"))
  );

  const familyMap = new Map();

  metadataFiles.forEach((item) => {
    const family = familyFromPath(item.path);
    if (!family) return;

    familyMap.set(family, {
      family,
      category: guessCategory(item.path),
      favorite: marketingFavorites.includes(family),
      popularity: marketingFavorites.includes(family)
        ? marketingFavorites.indexOf(family) + 1
        : 9999,
      tags: tagMap[family] || [],
    });
  });

  const fonts = Array.from(familyMap.values()).sort((a, b) => {
    if (a.favorite && !b.favorite) return -1;
    if (!a.favorite && b.favorite) return 1;
    return a.family.localeCompare(b.family);
  });

  const outputPath = path.join(__dirname, "../src/data/googleFonts.js");

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });

  const fileContent = `// Auto-generated by scripts/generateGoogleFonts.js
// Local Google Fonts catalog for AdGen MCM.

const googleFonts = ${JSON.stringify(fonts, null, 2)};

export default googleFonts;
`;

  fs.writeFileSync(outputPath, fileContent);

  console.log(`Generated ${fonts.length} fonts at src/data/googleFonts.js`);
}

main().catch((err) => {
  console.error("Failed to generate Google Fonts catalog:", err);
  process.exit(1);
});